### ISSUE TITLE
So uhm.. no updates? (Beat Saber 1.18.0)

### ISSUE THREAD

**Issue by AndrewTheWolfdog** [Auros/DiSounds#12]
Beat Saber 1.18.0 just updated a week ago and I installed this, but it's not working nor it's not capable? What does it mean? Otherwise, will there still be an update?

**Comment by Auros** [comment]
I haven't had much time to work on it, I'm currently on a break from Beat Saber modding, and in the future I plan to give it a needed overhaul. There is no planned update at the moment.
